<!-- 
/**
 * Blackbird AjaxVatChecker Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category            Blackbird
 * @package		Blackbird_AjaxVatChecker
 * @copyright           Copyright (c) 2015 Blackbird (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

 -->
<script type="text/javascript">
    var ajaxvatchecker_selectors = '<?php echo str_replace(':', '\\\:', Mage::getStoreConfig('blackbird_ajaxvatchecker/general_settings/cssselectors')); ?>';
    var ajaxvatchecker_selectors_country = '<?php echo str_replace(':', '\\\:', Mage::getStoreConfig('blackbird_ajaxvatchecker/general_settings/country')); ?>';
    var ajaxvatchecker_controller = '<?php echo $this->getUrl('ajaxvatchecker'); ?>';
    var ajaxvatchecker_validmessage = '<div class="ajaxvatchecker-validating-message validation-advice" style="display:none;"></div>';

</script>

