<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses
 */
$fileHtml = $this->getFileUploadsToHtml();
if($fileHtml): ?>
    <table cellspacing="0" id="filesOnQuoteView" class="form-list" border="0">
        <tbody>
        <tr>
            <th style="width:150px; vertical-align:middle;">
                <h4>
                    <?php echo $this->__('Attachments') ?>
                </h4>
            </th>
        </tr>
        <?php
        // Displays multiple lines
        echo $fileHtml;
        ?>
        </tbody>
    </table>
<?php endif; ?>
