<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php
/**
 * @var Ophirah_Qquoteadv_Block_Renderers_Bundle $this
 */
?>
<div class="product-details">
    <?php if ($this->hasBundleOptions()): ?>
        <div class="configurable-options">
            <ul>
                <?php foreach ($this->getBundleOptions() as $bundleOption): ?>
                    <li><span class="option-header"><?php echo $bundleOption['label'] ?></span></li>
                    <?php foreach ($bundleOption['value'] as $bundleValue): ?>
                        <li><span class="option-item"><?php echo $bundleValue['qty'] ?><span class="qty-cross">x</span>  <?php echo $bundleValue['title'] ?>
                                + <?php echo Mage::helper('core')->formatPrice($bundleValue['price'], true, false); ?></span>
                        </li>
                        <!--<li><span class="option-item"><?php echo Mage::helper('qquoteadv')->__('Qty:')?> <?php echo $bundleValue['qty'] ?></span></li>-->
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
    <?php if ($this->hasOptions()): ?>
        <dl class="item-options">
            <?php foreach ($this->getOptions() as $value): ?>
                <dt><?php echo $this->escapeHtml($value['label']) ?></dt>
                <dd><?php echo $this->escapeHtml($value['value']) ?></dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php if($this->getError()): ?>
        <div id="add-to-quote-errors" style="display: none;">
            <?php echo $this->getError(); ?>
        </div>
    <?php endif; ?>
</div>
