<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php
/**
 * @var Ophirah_Qquoteadv_Block_Renderers_Grouped $this
 */
?>
<?php foreach ($this->getQuote()->getItemsCollection() as $quoteItem): ?>
    <div class="grouped-product-container grouped-product">
        <div class="product-details">
            <div class="configurable-options">
                <ul>
                    <li><h2><?php echo $quoteItem->getName() ?></h2></li>
                    <li>
                        <span class="option-item"><?php echo Mage::helper('qquoteadv')->__('Price') ?>:
                            <?php echo $this->getProductPrice($quoteItem->getProduct()); ?>
                        </span>
                    </li>
                    <li class="option-header-border">
                        <span class="option-item">
                            <?php echo Mage::helper('qquoteadv')->__('Qty')?>: <?php echo $quoteItem->getQty() ?>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php if ($this->hasOptions()): ?>
    <dl class="item-options">
        <?php foreach ($this->getOptions() as $value): ?>
            <dt><?php echo $this->escapeHtml($value['label']) ?></dt>
            <dd><?php echo $this->escapeHtml($value['value']) ?></dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
<?php if($this->getError()): ?>
    <div id="add-to-quote-errors" style="display: none;">
        <?php echo $this->getError(); ?>
    </div>
<?php endif; ?>
