<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.2 or later
 *
 * @category MageTrend
 * @package  MT/Exitoffer
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/exit-intent-popup
 */
?>
<?php if ($this->isActivePopUp()): ?>
<?php $contentType = $this->getContentType(); ?>
<div id="mteo_popup_bg_layer">
    <div id="mteo_popup_content">
        <?php if ($contentType == MT_Exitoffer_Model_Popup::CONTENT_TYPE_STATIC_CMS_BLOCK):?>
            <?php echo $this->getStaticBlockHtml(); ?>
        <?php else: ?>
            <?php echo $this->getPopupContentHtml(); ?>
        <?php endif; ?>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        exitOffer.init(<?php echo $this->getConfigJs(); ?>);
    });
</script>
<?php endif; ?>