<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.2 or later
 *
 * @category MageTrend
 * @package  MT/Exitoffer
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/exit-intent-popup
 */
?>
<div class="mteo-theme-default mteo_content_<?php echo $this->getContentType();?>" style="background-color: <?php echo $this->getColor(1);?>">
    <a class="mteo-popup-close mteo-close" href="#"></a>
    <?php echo $this->getChildHtml($this->getContentType());?>
</div>
