
<?php if(Mage::getVersion() < '1.9.3'): ?>
<script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/product.js') ?>" type="text/javascript"></script>
</script> 
<?php else:?>
    <script src="<?php echo $this->helper('core/js')->getJsUrl('lib/uploader/flow.min.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->helper('core/js')->getJsUrl('lib/uploader/fusty-flow.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->helper('core/js')->getJsUrl('lib/uploader/fusty-flow-factory.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->helper('core/js')->getJsUrl('mage/adminhtml/uploader/instance.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/product1.9.3.js') ?>" type="text/javascript"></script>
    

<?php endif;
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content
 */
?>
<?php
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<?php 
//dout($_block->debug());
?>

<style>
#media_gallery_content_grid_cpa .last, #media_gallery_content_grid_cpa .cell-disable {
	display:none;
}
</style>

<div id="<?php echo $_block->getHtmlId() ?>" >
<div class="grid">
<table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid_gallery" width="100%">
    <col width="120" />
    <col />
    <col width="100" />
    <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
<!--    <col />-->
    <?php endforeach; ?>
    <col width="70" />
    <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('photogallery')->__('Image') ?></th>
            <th><?php echo Mage::helper('photogallery')->__('Image Name') ?></th>
            <th><?php echo Mage::helper('photogallery')->__('Alt Text') ?></th>
            <th><?php echo Mage::helper('photogallery')->__('Image Caption') ?></th>
            <th><?php echo Mage::helper('photogallery')->__('Sort Order') ?></th>
            <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
            	<?php //echo $type['label'] ?>
            <?php endforeach; ?>
            <th><?php echo Mage::helper('photogallery')->__('Delete') ?></th>
            
            <th class="last"><?php echo Mage::helper('photogallery')->__('Disable') ?></th>
        </tr>
    </thead>
    <tbody id="<?php echo $_block->getHtmlId() ?>_list">
        <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                <td class="cell-image"><div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')"><span><?php echo Mage::helper('photogallery')->__('Roll Over for preview') ?></span></div><img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" /></td>
                <td class="cell-label "><input type="text" class="input-text validate-alphanum-with-spaces" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>

                <td class="cell-alt "><input type="text" class="input-text  validate-alphanum-with-spaces" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-description"><textarea  class="input-text  validate-length  maximum-length-160" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')"></textarea>
                <?php echo Mage::helper('photogallery')->__('Maximum Limit for Caption is 160 Characters') ?>
                </td>
                <td class="cell-position"><input type="text" class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
	                <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
	                	<td class="cell-<?php echo $typeId ?> a-center" style="display:none;">
	                		<input type="hidden" name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('__file__')" value="__file__" /></td>
	                <?php endforeach; ?>
                <td class="cell-remove a-center"><input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-disable a-center  last"><input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
        </tr>

        <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                <td class="cell-image"><?php echo Mage::helper('catalog')->__('No image') ?></td>
                <td class="cell-label"><input type="hidden" />&nbsp;</td>
                <td class="cell-alt"><input type="hidden" />&nbsp;</td>
                <td class="cell-description"><input type="hidden" />&nbsp;</td>
                <td class="cell-position"><input type="hidden" />&nbsp;</td>
	                <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
	                	<td class="cell-<?php echo $typeId ?> a-center" style="display:none;">
	                		<input type="hidden" <?php //if($_block->getElement()->getAttributeReadonly($typeId)) :?> disabled="disabled" <?php //endif;?> name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('no_selection')" value="no_selection" /></td>
	                <?php endforeach; ?>
                <td class="cell-remove"><input type="hidden" />&nbsp;</td>
                <td class="cell-disable"><input type="hidden" />&nbsp;</td>
                
        </tr>
    </tbody>

                
    <tfoot>
        <tr>
            <td colspan="100" class="lasta" style="padding:8px">
                <?php echo $_block->getUploaderHtml() ?>
            </td>
        </tr>
    </tfoot>

                
</table>
</div>
</div>
<?php //echo $_block->htmlEscape($_block->getImagesJson()) ?>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php //echo $_block->getElement()->getName() ?>photogallery_images" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="smece_save" name="[smece]" value="smece" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php //echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<?php if(Mage::getVersion() >= '1.9.3'): ?>  
<script type="text/javascript">
//<![CDATA[
var <?php echo $_block->getJsObjectName(); ?> = new Product.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getImageTypesJson() ?>);
//]]>
</script>
<?php else :?>
<script type="text/javascript">
//<![CDATA[
var <?php echo $_block->getJsObjectName(); ?> = new Product.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getUploader()->getJsObjectName() ?>, <?php echo $_block->getImageTypesJson() ?>);
//]]>
</script>
<?php endif ?>
<pre>
<?php 
//zend_debug::dump($_block->getImagesJson());
?>
</pre>
<pre>
<?php 
//zend_debug::dump($_block->getImagesValuesJson());
?>
</pre>
<?php 
//dout($_block->getImageTypes());
?>

