<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.2 or later
 *
 * @category MageTrend
 * @package  MT/Exitoffer
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/exit-intent-popup
 */
?>
<?php $additionalFields = $this->getAdditionalFields(); ?>
<?php $helper = Mage::helper('exitoffer'); ?>
<div  id="mteo_subcription_form" class="mteo-form-with-additional">
    <?php if ($this->getText(1)): ?>
    <div class="mteo-text-row-1" style="color: <?php echo $this->getColor(2); ?>">
        <?php echo $this->getText(1) ?>
    </div>
    <?php endif; ?>

    <?php if ($this->getText(2)): ?>
    <div class="mteo-text-row-2" style="color: <?php echo $this->getColor(2); ?>">
        <?php echo $this->getText(2) ?>
    </div>
    <?php endif; ?>


    <div class="mteo-subscribe">
        <?php if ($this->getText(3)): ?>
            <div class="mteo-text-row-3" style="color: <?php echo $this->getColor(2); ?>">
                <?php echo $this->getText(3) ?>
            </div>
        <?php endif; ?>
        <input class="mt-validator-required mt-validator-email" data-field-name="<?php echo $helper->translate('email'); ?>" onclick="if(this.value=='<?php echo $helper->translate('email'); ?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $helper->translate('email'); ?>'" id="mteo_email" name="subscribe_email" value="<?php echo $helper->translate('email'); ?>" type="text">

        <?php if ($additionalFields): ?>
                <?php foreach ($additionalFields as $field): ?>
                        <?php echo $field->getHtml();?>
                <?php endforeach;?>
            <?php endif;?>

            <a style="background-color: <?php echo $this->getColor(3);  ?>; color: <?php echo $this->getColor(2); ?>" href="javascript:void(0)" id="mteo_contact_submit" ><?php echo $helper->translate('send'); ?></a>

    </div>
    <div id="mteo_msg_error" style="color: <?php echo $this->getColor(2); ?>"></div>
</div>

<div id="mteo_subscription_success_with_coupon">
    <div id="mteo_msg_success" style="color: <?php echo $this->getColor(2); ?>"></div>
    <div id="mteo_coupon">
        <div id="mteo_coupon_code" style="background-color: <?php echo $this->getColor(2);?>; border-color: <?php echo $this->getColor(3);?>"><?php echo $helper->translate('coupon');?> <span>df56s5d8</span></div>
        <div class="mteo-box-shop-now-button"><a style="color: <?php echo $this->getColor(2); ?>; background-color: <?php echo $this->getColor(3); ?>" class="mteo-close" href="#" style=""><?php echo $helper->translate('shop_now'); ?></a> </div>
    </div>
</div>

<div id="mteo_subscription_success">
    <div class="mteo-success-msg" style="color: <?php echo $this->getColor(2); ?>"></div>
</div>