<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.2 or later
 *
 * @category MageTrend
 * @package  MT/Exitoffer
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/exit-intent-popup
 */
?>
<input
    name="<?php echo $this->getName();?>"
    type="hidden"
    value="<?php echo $this->getDefaultValue();?>"
    class="mteo-additional-field mteo-additional-field-<?php echo $this->getName();?>"
    data-field-name="<?php echo $this->getTitle()?>"
    id="mteo_additional_<?php echo $this->getName();?>"
    />
