<?php
/**
 * Media Photogallery & Product Gimages extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>

<?php
    $blockdata = $this->getActiveBlock(); 
    $config = Mage::getModel('photogallery/image_configimg');
    $image = Mage::getModel('media/image');
    $image->setConfig($config);

?>
<?php if (count($blockdata)) : ?>
<?php
    $relatedImages = $this->getBlockImages($blockdata['photogallery_block_id'])->getData();
    // echo "<pre>"; print_r($relatedImages); exit();
    $currentItems = count($relatedImages);
    $totalPages= ceil($this->getImageCount()/$currentItems);
    
?>


<!--<h6><?php //echo Mage::helper('photogallery')->__($blockdata['block_title']); ?></h6>-->
<!--<span class="text4"><?php //echo Mage::helper('photogallery')->getWysiwygFilter($blockdata['block_content']); ?></span>-->


<?php if ( count($relatedImages) ) { ?>


<div class="wrapper" style="min-width: 100%;">

            <div id="grid-container" class="cbp-l-grid-projects">
                <ul>
                        
         <?php $firstCount = 1; ?>
        <?php $i=0; foreach ($relatedImages as $item): ?>
            <?php
            
            
            $imageFile =  Mage::getBaseUrl('media').'gallery/galleryimages/'.$item["blockimage_name"];
            ?>
        <li class="<?php echo 'cbp-item '. $item['blockimage_id'];?>">
             
                <div class="cbp-caption">
                
        <div class="cbp-caption-defaultWrap">
        <img src="<?php echo $imageFile; ?>" alt="<?php echo $item['alt_text']?>" width="100%" height="100%">
        </div>
            
            
                            <div class="cbp-caption-activeWrap">
                                <div class="cbp-l-caption-alignCenter">
                                    <div class="cbp-l-caption-body">
                                        <a href="<?php echo $imageFile ?>" class="cbp-lightbox cbp-l-caption-buttonRight" data-title=""><?php echo $this->__('View larger') ?></a>
                                    </div>
                                </div>
                            </div>
                                        </div>
                <?php if($blockdata['enablecontent'] != 0 && trim($item['blockimage_label']) !='') { ?>
                
                <div class="cbp-l-grid-projects-title"><?php echo $item['blockimage_label'];?></div>
                <div class="cbp-l-grid-projects-desc"><?php echo $item['img_description'];?></div>
                <?php } ?>
            </li>
            <?php $firstCount++; ?>
        <?php endforeach ?>
        
       
        
                </ul>
            </div>
           
            <?php //echo $this->_itemsOnPage; ?>
            <?php if($this->getLastPageNum()>1): ?>
                    <?php  $_pages = count($this->getPages());?>
                        <?php  foreach ($this->getPages() as $_page): ?>
                                <?php if ($this->isPageCurrent($_page)): ?>
                                    <?php $_page++;?>
                                <div class="cbp-l-loadMore-button">
                                    <a href="<?php echo Mage::getUrl('photogallery/index/ajaxBlockPagination', array('page' => $_page,'pages' =>$_pages,'blockId'=>$blockdata['photogallery_block_id']))?>" class="cbp-l-loadMore-button-link"><?php echo Mage::getStoreConfig('photogallery/photogallery/pagertext')?></a>
                                </div>
                                <?php else: ?>
                                <?php endif;?>
                        <?php endforeach; ?>
                <?php endif;?>



 </div>




<script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/script/jquery-1.9.1.min.js') ?>" type="text/javascript"></script>


<script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/script/cubeportfoliojs.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/script/main.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->helper('core/js')->getJsUrl('fmegallery/script/jquery.confy.js') ?>" type="text/javascript"></script>





<?php } ?>


<?php endif; ?>