<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php $product = $this->getSelectedProduct(); ?>
<?php $products = $this->getProducts(); ?>
<?php $errors = $this->getData('errors'); ?>

<div class="qquoteadv">
    <div class="introduction">
        <div class="large-text-ajax"><?php echo Mage::helper('qquoteadv')->__('Added to your Quote List'); ?></div>
    </div>
    <?php
    if (is_array($products) && !empty($products)) {
        foreach ($products as $ajaxProduct) {
            echo '<div class="grouped-product-container">' . $this->getItemHtml($ajaxProduct) . '</div>';
        }
    } else {
        echo $this->getItemHtml($product);
    }
    ?>
</div>
<div class="button-container">
    <button type="button" onclick="cancelMsg();Miniquote.reloadContent();"
            title="<?php echo Mage::helper('customer')->__('Continue Shopping'); ?>" class="button btn-cart">
        <span>
            <span><?php echo Mage::helper('customer')->__('Continue Shopping'); ?></span>
        </span>
    </button>
    <button type="button" onclick="document.location.href='<?php echo Mage::getUrl('qquoteadv/index'); ?>'"
            title="<?php echo Mage::helper('qquoteadv')->__('View Quote List'); ?>" class="button btn-cart">
        <span>
            <span><?php echo Mage::helper('qquoteadv')->__('View Quote List'); ?></span>
        </span>
    </button>
</div>
