<?php $mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<div class="col-xs-24" id="productFooter">
<a href="<?php echo Mage::getBaseUrl() ?>swatches.html"><img src="<?php echo $mediaUrl; ?>images/swatches.jpg" alt="Request A Swatch" class="img-responsive swatch-image" /></a>
<a href="<?php echo Mage::getBaseUrl() ?>swatches.html"><h3 class="overlay-text"><?php echo $this->__('Request Swatch'); ?></h3></a>
</div>