<?php

/**
 * MageWorx
 * CustomOptions Extension
 * 
 * @category   MageWorx
 * @package    MageWorx_CustomOptions
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
$item   = $this->getItem();
if ($item) { ?>
<div class="container-swatch-color small-image-preview v-middle<?php if ($item->getClass()) echo ' '.$item->getClass(); ?>">
    <div class="swatch-color" style="background:<?php echo $item->getColor() ?>;">&nbsp;</div>
</div>
<?php } ?>