<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     CustomProducts
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 * @version     1.0.5
 */
?>
<?php
/** @var $this Ophirah_Qquoteadv_Block_Qquoteadv_Email_Item */
$product = $this->getProduct();
$item = $this->getItem();
?>
<?php if (isset($product)
    && !empty($product)
    && ($product->getSku() == Ophirah_CustomProducts_Helper_Data::PRODUCT_SKU)
): ?>

    <?php $productValues = Mage::getModel('customproducts/customproduct')->getProductOptionValues($item->getAttribute()); ?>

    <tr>
        <td align="left" valign="center" style="padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php if ($productValues->getImageUrl()): ?>
                <img src="<?php echo $productValues->getImageUrl()?>"
                     alt="<?php echo $productValues->getName(); ?>"
                     width="75"/>
            <?php endif; ?>
        </td>
        <td align="left" valign="top" style="padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <strong style="font-size:11px;"><?php echo $productValues->getName() ?></strong>
            <?php if ($productValues->hasDescription()): ?>
                <dl style="margin:0; padding:0;">
                    <dd style="margin:0; padding:0 0 0 9px;">
                        <?php $productDescription = $productValues->getDescription(); ?>
                        <?php echo (!empty($productDescription)) ? $productDescription : nl2br($this->escapeHtml($productDescription)); ?>
                    </dd>
                </dl>
            <?php endif; ?>
        </td>
        <td align="left" valign="top"
            style="padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $productValues->getSku() ?></td>
        <?php
        $reqData = $this->getRequestedProductData($item->getId(), $item->getQuoteId());
        $prices = $reqData['ownerPrices'];
        $aQty = $reqData['aQty'];
        ?>
        <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php if (count($aQty)): ?>
                <?php foreach ($aQty as $key => $value): ?>
                    <div style="height:25px;" align="center"><?php echo $value*1; ?></div>
                <?php endforeach; ?>
            <?php endif; ?>
        </td>
        <td align="center" valign="top" style="font-size:11px; padding:3px 9px;  border-bottom:1px dotted #CCCCCC;">
            <?php if (count($prices)): ?>
                <?php foreach ($prices as $key => $value): ?>
                    <div style="height:25px;"><?php echo Mage::helper('checkout')->formatPrice($value); ?></div>
                <?php endforeach; ?>
            <?php endif; ?>
        </td>
        <?php $merge = array_combine($aQty, $prices); ?>
        <td align="right" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php foreach ($merge as $qty => $price): ?>
                <?php $total = Mage::helper('checkout')->formatPrice($qty * $price); ?>
                <div style="height:25px;"><?php echo $total; ?></div>
            <?php endforeach; ?>
        </td>
    </tr>
<?php endif; ?>
