<div id="aitcg_color_set_editor"></div>

<script type="text/javascript">
    
    var colorsetEditor = new Aitcg_ColorSet_Editor({
        source: $('edit_form')['value'],
        labels: $('edit_form')['label'],
        container: $('aitcg_color_set_editor'),
        initVarName: 'colorsetEditor',
        colorAddText: '<?php echo Mage::helper('aitcg')->__('Add Color') ?>'
    });
    
    colorsetEditor.renderSet();
</script>