<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php
if ($this->getQuote()) {
    $quoteModel = $this->getQuote();
}

$status = $quoteModel->getData('status');
$storeId = $quoteModel->getData('store_id');

$btnCreateOrder = $this->getLayout()->createBlock('adminhtml/widget_button');
$btnCreateOrder->setLabel(Mage::helper('sales')->__('Create Order'));
$btnCreateOrder->setClass('save');

$onclick = "event.preventDefault(); if (isCheckRadio()) { $('redirect2neworder').value=1; $('loading-mask').show(); save(); } else { return false; }";
$btnCreateOrder->setOnclick($onclick);
?>

<?php
$button = $this->getLayout()->createBlock('adminhtml/widget_button');
// Check if quote is allowed for negative profit
$profitSetting = Mage::getStoreConfig('qquoteadv_quote_configuration/proposal/profit', $storeId);
$profit = ($profitSetting == 1) ? true : false;
if ($quoteModel->getData('no_profit') == 1 && $profit === false) {
    $button->setLabel($this->__('No profit, increase Price(s)'));
} else {
    $button->setLabel($this->__('Submit Quote'));
}
$button->setClass('save');

if ($status == Ophirah_Qquoteadv_Model_Status::STATUS_ORDERED ||
    $status == Mage::getModel('qquoteadv/status')->getStatusConfirmed() ||
    $status == Ophirah_Qquoteadv_Model_Status::STATUS_PROPOSAL_SAVED ||
    ($quoteModel->getData('no_profit') == 1 && $profit === false)
) {
    $button->setClass('disabled');
    $button->setOnclick("return false;");
} else {
    $onclick = "event.preventDefault(); $('loading-mask').show(); saveAndContinueEdit();";
    $button->setClass();
    $button->setOnclick($onclick);
}
?>

<?php
$html = '';
if (Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_BUTTONS)):
    $html .= $this->getChildHtml('bidding.button') . '&nbsp;&nbsp;';
    if (Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_BUTTONS_SUBMIT_PROPOSAL)):
        $html .= $button->_toHtml() . '&nbsp;&nbsp;';
    endif;
    if (Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_BUTTONS_CREATE_ORDER)):
        $html .= $btnCreateOrder->_toHtml();
    endif;
endif;

echo $html;
?>

