<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION)): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->__('Quote # %s', $quoteModel->getData('increment_id') ? $quoteModel->getData('increment_id') : $quoteModel->getData('quote_id')) ?>
        </h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0">
                <tbody>
                <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION_LAST_UPDATE)): ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adminnotification')->__('Last Update') ?></label></td>
                    <td class="value">
                        <strong><?php echo $this->formatDate($quoteModel->getData('updated_at'), 'medium', true) ?></strong>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION_QUOTE_REQUEST_STATUS)): ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Quote Status') ?></label></td>
                    <td class="value">
                        <strong>
                                <span id="quote_status">
                                    <?php
                                    $substatus = ($quoteModel->getData('substatus')) ? $quoteModel->getData('substatus') : '';
                                    $status = Mage::getModel('qquoteadv/substatus')->getCurrentStatus($quoteModel->getData('status'), $substatus);
                                    $disabled = ($quoteModel->getData('status') == Ophirah_Qquoteadv_Model_Status::STATUS_PROPOSAL_SAVED) ? 'disabled' : '';
                                    echo '<select ' . $disabled . ' name="status" >';
                                    foreach (Mage::getModel('qquoteadv/status')->getOptionArray(true) as $k => $v):
                                        $selected = ($status == $v) ? "selected = selected" : '';
                                        echo '<option value="' . $k . '" ' . $selected . '>' . $v . '</option>';
                                    endforeach;
                                    echo '</select>';
                                    ?>
                                </span>
                        </strong>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION_RFQ_FROM)): ?>
                <tr id="rfq_current">
                    <td class="label"><label><?php echo $this->__('RFQ From') ?></label></td>
                    <td class="value">
                        <strong><?php echo $this->getStoreViewInfo($quoteModel->getData('store_id')); ?></strong></td>
                </tr>
                <tr>
                    <td class="label" id="label_dropdown" style="display:none"><label><?php echo $this->__('RFQ From') ?></label></td>
                    <td class="value" id="rfq_dropdown" style="display:none;">
                        <?php $currentStore = $quoteModel->getData('store_id'); ?>
                        <?php echo '<select ' . $disabled . ' name="store" id="store">'; ?>
                        <?php foreach ($this->getQuoteWebsites() as $website): ?>
                            <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                            <?php foreach ($website->getGroups() as $group): ?>
                                <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                                    <?php foreach ($this->getLayout()->getBlockSingleton('Mage_Adminhtml_Block_Store_Switcher')->getStores($group) as $store): ?>
                                        <option
                                            value="<?php echo $this->escapeHtml($store->getId()) ?>"<?php if ($currentStore == $store->getId()): ?> selected="selected"<?php endif; ?>>
                                            &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                        <?php echo '</select>'; ?>
                    </td>
                    <td></td>
                    <?php if ($this->countStoreviews() > 1):?>
                        <td id="rfq_change" style="padding: 5px;">
                            <a href="#" onclick="event.preventDefault();changeStore()">
                                <?php echo Mage::helper('catalog')->__('Change')?>
                            </a>
                        </td>
                    <?php endif;?>
                </tr>
                <tr>
                    <td></td>
                    <td id="rfq_cancel" style="padding: 5px; display:none">
                        <a href="#" onclick="event.preventDefault();cancelStoreChange()">
                            <?php echo Mage::helper('catalog')->__('Cancel')?>
                        </a>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION_LINK_TO_NEW_QUOTE)): ?>
                <?php if($quoteModel->getRelationChildId()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('qquoteadv')->__('Link to the New Quote') ?></label></td>
                        <td class="value">
                            <?php $childQuoteIds = $quoteModel->getRelationChildRealIds();
                            foreach($childQuoteIds as $childQuoteId => $childQuoteIncrementId): ?>
                            <a href="<?php echo $this->getUrl('*/qquoteadv/*', array('id' => $childQuoteId)) ?>">
                                <?php echo $childQuoteIncrementId ?>
                            </a>&nbsp;
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php endif; ?>
                <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_GENERAL_QUOTE_INFORMATION_LINK_TO_PREVIOUS_QUOTE)): ?>
                <?php if($quoteModel->getRelationParentId()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('qquoteadv')->__('Link to the Previous Quote') ?></label></td>
                        <td class="value"><a href="<?php echo $this->getUrl('*/qquoteadv/*', array('id' => $quoteModel->getRelationParentId())) ?>">
                                <?php echo $quoteModel->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    /**
     * @description Shows request for quote store switch dropdown list. Hides current store details
     */
    function changeStore() {
        $('rfq_dropdown').show();
        $('label_dropdown').show();
        $('store').disabled=false;
        $('rfq_cancel').show();
        $('rfq_current').hide();
        $('rfq_change').hide();
    }
    /**
     * @desciption Hides request for quote store switch dropdown. Shows current store details
     */
    function cancelStoreChange(){
        $('rfq_dropdown').hide();
        $('store').disabled=true;
        $('label_dropdown').hide();
        $('rfq_cancel').hide();
        $('rfq_current').show();
        $('rfq_change').show();
    }
</script>
<?php endif; ?>
