<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2020] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2020 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<td class="<?php echo $this->getCssContentClasses()?>">
    <?php $tierMatch = false;
    if ($this->getTierQty()->count()): ?>

        <?php if(Ophirah_Qquoteadv_Helper_Acl::allowed(Ophirah_Qquoteadv_Helper_Acl::VIEW_ADD_QTY)): ?>
            <?php foreach ($this->getTierQty() as $requestedItem): ?>
                <div style="height:25px;"><?php echo number_format($requestedItem->getRequestQty(), 2) . '<input type="hidden" name="product[' . $requestedItem->getId() . '][qty]" value="' . $requestedItem->getRequestQty() . '">'; ?></div>
                <?php echo '<input type="hidden" name="product[' . $requestedItem->getId() . '][requestedproduct]" value="' . $this->getItem()->getId() . '">'; ?>
            <?php endforeach; ?>
            <a href="#"
               onclick="typeQty('<?php echo $this->getItem()->getId() ?>')"><?php echo Mage::helper('sales')->__('Add') ?></a>
        <?php else: ?>
            <div style="height:25px;"><?php echo number_format($this->getItem()->getQty(), 2); ?></div>
        <?php endif; ?>
    <?php endif; ?>
</td>

